name: CI

on:
  pull_request:
  push:
    branches: [ main ]

test:
  runs-on: ubuntu-latest

  steps:
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Setup and Prepare Database
      run: |
        bin/rails db:create
        bin/rails db:schema:load
        bin/rails db:test:prepare

    - name: Run RSpec tests
      env:
        RAILS_ENV: test
      run: bundle exec rspec

    - name: Keep screenshots from failed system tests
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots
        path: ${{ github.workspace }}/tmp/screenshots
        if-no-files-found: ignore

